### ISSUE TITLE
bug in overrides parsing(?)

### ISSUE THREAD

**Issue by axgkl** [barrientosvctor/abyss.nvim#26]
https://github.com/barrientosvctor/abyss.nvim/blob/7afb3cabdc83c208b77cc228896b2966118f6b3e/lua/abyss/util.lua#L30

should be not `==0` but `>0` I guess(?) 
I think you can omit the line completely.

**Comment by barrientosvctor** [comment]
Oh my bad, you're right! I didn't notice about this bug.

I'll change it to be `> 0`, my idea about this conditional is to make sure if the table has some overrides, if so, apply them to the colorscheme.

Thanks for creating this issue!
