### ISSUE TITLE
Inlay hints seems not work well

### ISSUE THREAD

**Issue by tan-wei** [barrientosvctor/abyss.nvim#35]
![图片](https://github.com/user-attachments/assets/a3255f4f-03c0-4f02-ba18-c53727761198)

**Comment by barrientosvctor** [comment]
Hello, I found the missing highlight group, I'll fix that now.

Thanks for contributing!

**Comment by tan-wei** [comment]
Great! Confirmed it is solved.

Thanks!

**Comment by barrientosvctor** [comment]
Thank you for your notice about this issue!
